### ISSUE TITLE
Provisioning Error

### ISSUE THREAD

**Issue by the-pinky-man** [directus/directus-vagrant#16]
Hi there,

I am getting the following provisioning error:

_==> default: PHP Warning:  mysqli::mysqli(): (28000/1045): Access denied for user 'directus'@'localhost' (using password: YES) in /var/www/html/directus/vendor/directus/migrations/lib/Ruckusing/Adapter/MySQL/MySQLBase.php on line 1294
==> default: PHP Fatal error:  Uncaught
==> default: MySQLBase.php(1296) :
==> default:
==> default: Could not connect to the DB, check host / user / password
==> default:
==> default:
==> default:
==> default:   thrown in /var/www/html/directus/vendor/directus/migrations/lib/Ruckus                                                                                     ing/Adapter/MySQL/MySQLBase.php on line 1296_

This is on the master of the repo, using win10 and vagrant 1.8.1

Any ideas?

Thanks
Mat

**Comment by WellingGuzman** [comment]
Thanks @pimj001 for reporting this, I will take a look at this issue.

**Comment by WellingGuzman** [comment]
Still no being able to replicate it, I will try on a new machine. Probably test it on a win10 machine.

**Comment by pimj001** [comment]
Interesting. I will also try on 16.04 and see if I have issues there... 

It worked on win10 about a month ago no problems.

**Comment by the-pinky-man** [comment]
@WellingGuzman Just repeated the issue on Ubuntu 16.04 x64, Vagrant 1.81. 

The provisioning bombed with the same error as above.

**Comment by luissantos** [comment]
@WellingGuzman Check this 
https://github.com/directus/directus-vagrant/pull/17

**Comment by WellingGuzman** [comment]
Hi @the-pinky-man can you confirm that https://github.com/directus/directus-vagrant/pull/17 fixed the issue?

Thanks @luissantos

**Comment by the-pinky-man** [comment]
@WellingGuzman yep works for me.

**Comment by WellingGuzman** [comment]
Excellent @the-pinky-man.
