### ISSUE TITLE
Failed to start vagrant URL not found

### ISSUE THREAD

**Issue by moalfa** [directus/directus-vagrant#18]
after "vagrant up" I get the following error:
`Downloading: http://demo.getdirectus.com/vagrant/directus`
` The requested URL returned error: 404 Not Found`

It seems that Vagrant box is moved somewhere else.
[http://demo.getdirectus.com/vagrant/directus](http://demo.getdirectus.com/vagrant/directus)

**Comment by WellingGuzman** [comment]
Thanks for reporting this @moalfa, I'm working on this.

**Comment by WellingGuzman** [comment]
@moalfa Link fixed!
