### ISSUE TITLE
PHP / zend-stdlib  Version Misalignment?

### ISSUE THREAD

**Issue by alexgraul** [directus/directus-vagrant#21]
Hello,

Attempting a fresh install on OSX10.11.5, vagrant 1.9.1, Virtualbox 5.1.14
Followed the instructions, cloned, ran vagrant up and got a series of errors about the provided version of PHP not matching requirements for the zend-stdlib dependency:
`zendframework/zend-stdlib 3.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.`

Full log below.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'directus'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'directus' is up to date...
==> default: Setting the name of the VM: directus-vagrant_default_1486638497714_2989
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Remote connection disconnect. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
    default: The guest additions on this VM do not match the installed version of
    default: VirtualBox! In most cases this is fine, but in rare cases it can
    default: prevent things such as shared folders from working properly. If you see
    default: shared folder errors, please make sure the guest additions within the
    default: virtual machine match the version of VirtualBox you have installed on
    default: your host and reload your VM.
    default: 
    default: Guest Additions Version: 4.3.10
    default: VirtualBox Version: 5.1
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/<username>/code/directus-vagrant
    default: /var/www/html => /Users/<username>/code/directus-vagrant/html
==> default: Running provisioner: shell...
    default: Running: /var/folders/1g/2865sjg12ds_6j7yg709v9wh0000gn/T/vagrant-shell20170209-3355-19r4moa.sh
==> default: stdin: is not a tty
==> default: Ign http://archive.ubuntu.com trusty InRelease
==> default: Get:1 http://archive.ubuntu.com trusty-updates InRelease [65.9 kB]
==> default: Get:2 http://security.ubuntu.com trusty-security InRelease [65.9 kB]
==> default: Hit http://archive.ubuntu.com trusty Release.gpg
==> default: Hit http://archive.ubuntu.com trusty Release
==> default: Get:3 http://archive.ubuntu.com trusty-updates/main Sources [391 kB]
==> default: Get:4 http://security.ubuntu.com trusty-security/main Sources [124 kB]
==> default: Get:5 http://security.ubuntu.com trusty-security/universe Sources [49.3 kB]
==> default: Get:6 http://archive.ubuntu.com trusty-updates/universe Sources [173 kB]
==> default: Get:7 http://security.ubuntu.com trusty-security/main amd64 Packages [579 kB]
==> default: Get:8 http://archive.ubuntu.com trusty-updates/main amd64 Packages [947 kB]
==> default: Get:9 http://security.ubuntu.com trusty-security/universe amd64 Packages [151 kB]
==> default: Get:10 http://security.ubuntu.com trusty-security/main Translation-en [320 kB]
==> default: Get:11 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [397 kB]
==> default: Get:12 http://security.ubuntu.com trusty-security/universe Translation-en [88.7 kB]
==> default: Get:13 http://archive.ubuntu.com trusty-updates/main Translation-en [467 kB]
==> default: Get:14 http://archive.ubuntu.com trusty-updates/universe Translation-en [210 kB]
==> default: Hit http://archive.ubuntu.com trusty/main Sources
==> default: Hit http://archive.ubuntu.com trusty/universe Sources
==> default: Hit http://archive.ubuntu.com trusty/main amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/universe amd64 Packages
==> default: Hit http://archive.ubuntu.com trusty/main Translation-en
==> default: Hit http://archive.ubuntu.com trusty/universe Translation-en
==> default: Ign http://archive.ubuntu.com trusty/main Translation-en_US
==> default: Ign http://archive.ubuntu.com trusty/universe Translation-en_US
==> default: Fetched 4,029 kB in 3s (1,077 kB/s)
==> default: Reading package lists...
==> default: Updating to version 07123715d6782185b25059871f272054057333c7.
==> default:     Downloading: Connecting...
==> default: 
==> default:     Downloading: 100%
==> default:          
==> default: 
==> default: Use composer self-update --rollback to return to version 9fb2d4f2d642a0749decb41bc2fe4be2bf8bef7a
==> default: Cloning into '/var/www/html/directus'...
==> default: /var/www/html/directus /home/vagrant
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default: Your requirements could not be resolved to an installable set of packages.
==> default: 
==> default:   Problem 1
==> default:     - Installation request for zendframework/zend-stdlib 3.2.x-dev -> satisfiable by zendframework/zend-stdlib[3.2.x-dev].
==> default:     - zendframework/zend-stdlib 3.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:   Problem 2
==> default:     - Installation request for zendframework/zend-stdlib dev-develop -> satisfiable by zendframework/zend-stdlib[dev-develop].
==> default:     - zendframework/zend-stdlib dev-develop requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:   Problem 3
==> default:     - zendframework/zend-stdlib 3.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:     - zendframework/zend-db dev-directus requires zendframework/zend-stdlib ^2.7 || ^3.0 -> satisfiable by zendframework/zend-stdlib[3.2.x-dev].
==> default:     - Installation request for zendframework/zend-db dev-directus -> satisfiable by zendframework/zend-db[dev-directus].
==> default: /home/vagrant
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by alexgraul** [comment]
PHP really isn't my space but a bit of digging suggests it's do with zend-db pulling a new version of zend-stdlib which requires PHP 5.6 as of https://github.com/zendframework/zend-stdlib/commit/1cb8170851f5d0a77c2fc6e95ace282928a4ccca#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780

**Comment by WellingGuzman** [comment]
Hey @alexgraul, the composer lock was generated using PHP 5.6, I pushed a fix with this commit https://github.com/directus/directus/commit/10a92a049d64f133c08fad16bdc81626938bb3cc.

You can solve it by:

- Removing `html/directus` and run `vagrant up` again.
or 
- Removing the `composer.lock` on `html/directus` and run manually `composer install`.

Hope it helps

**Comment by alexgraul** [comment]
Thankyou!

**Comment by WellingGuzman** [comment]
A note to anyone getting here.
Unfortunately we are going to stop supporting PHP 5.5, _as much as I want to keep 5.5 running in the next versions_, some packages requires PHP 5.6.

**Comment by the-pinky-man** [comment]
Gday @WellingGuzman, OK so I have also run into this issue after a fresh clone of the directus-vagrant repo - is there anything else I need to do?

Thanks

`==> default: /var/www/html/directus /home/vagrant
==> default: Do not run Composer as root/super user! See https://getcomposer.org/root for details
==> default: Loading composer repositories with package information
==> default: Installing dependencies (including require-dev) from lock file
==> default: Your requirements could not be resolved to an installable set of packages.
==> default:
==> default:   Problem 1
==> default:     - Installation request for zendframework/zend-stdlib 3.2.x-dev -> satisfiable by zendframework/zend-stdlib[3.2.x-dev].
==> default:     - zendframework/zend-stdlib 3.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:   Problem 2
==> default:     - Installation request for zendframework/zend-stdlib dev-develop -> satisfiable by zendframework/zend-stdlib[dev-develop].
==> default:     - zendframework/zend-stdlib dev-develop requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:   Problem 3
==> default:     - zendframework/zend-stdlib 3.2.x-dev requires php ^5.6 || ^7.0 -> your PHP version (5.5.9) does not satisfy that requirement.
==> default:     - zendframework/zend-db dev-directus requires zendframework/zend-stdlib ^2.7 || ^3.0 -> satisfiable by zendframework/zend-stdlib[3.2.x-dev].
==> default:     - Installation request for zendframework/zend-db dev-directus -> satisfiable by zendframework/zend-db[dev-directus].
==> default: /home/vagrant
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
==> default: PHP Warning:  require(/var/www/html/directus/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/directus/bin/directus on line 6
==> default: PHP Fatal error:  require(): Failed opening required '/var/www/html/directus/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/directus/bin/directus on line 6
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.`

**Comment by WellingGuzman** [comment]
@the-pinky-man try again, and let me know if it still happening to you.

**Comment by the-pinky-man** [comment]
@WellingGuzman I am retrying now, but I am guessing it will always have 5.5 since this is what is on the vagrant box.

**Comment by WellingGuzman** [comment]
@the-pinky-man I fixed the dependency version to 5.5, I tested it on php 5.5 now, and it should be working.

**Comment by the-pinky-man** [comment]
@WellingGuzman looks good thanks
