### ISSUE TITLE
Vagrant Box URL is Incorrect

### ISSUE THREAD

**Issue by enummela** [directus/directus-vagrant#25]
The Vagrant box URL seems to be incorrect:
https://demo.getdirectus.com/vagrant/directus

`vagrant up` command outputs the following error:
```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar: Error opening archive: Unrecognized archive format
```

**Comment by Moxxie** [comment]
Does anyone know the correct URL for a quickfix?

**Comment by benhaynes** [comment]
@WellingGuzman ?

**Comment by WellingGuzman** [comment]
Hey, we changed server and we were hosting the box ourselves. we are trying to get those files back. Also trying to move it to vagrant cloud.

**Comment by WellingGuzman** [comment]
Sorry for the long delay, I was having issue uploading this box over and over, but finally managed to get at least two version up `0.1.0` and `0.2.1`, but probably everyone should stick to `0.2.1`

Closed by https://github.com/directus/directus-vagrant/commit/6b50b4590a86e2b604914d339407351ced249040
