### ISSUE TITLE
Vagrant user not found

### ISSUE THREAD

**Issue by WellingGuzman** [directus/directus-vagrant#26]
Copied from https://github.com/directus/directus/issues/2026 by @jongirard

---
Installed using the vagrant installation option listed in the Directus docs. Installation successful but login with the provided credentials of ```admin@admin.com``` and password of ```admin``` fails with ```email not found```.

## Version Info
  - Directus version and branch: Directus Demo 0.1.1

## Steps to Reproduce
 1. Install via Vagrant
 2. Attempt to login with provided credentials in docs

**Comment by WellingGuzman** [comment]
After checking the docs (readme) latest. the credentials changed.

Can you check with **email**: `admin@getdirectus.com` **pass:** `password`

**Comment by tmikaeld** [comment]
Can you please update the docs with the new credentials?
